# Generated by Django 6.0.3 on 2026-07-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
